Lolo/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lolo.Models;
using Lolo.Models.Interfaces;
using Lolo.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Lolo.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogRepository _blogRepository;
        private readonly IPostRepository _postRepository;
        private UserManager<IdentityUser> _userManager;

        public BlogController(IBlogRepository blogRepository, IPostRepository postRepository, UserManager<IdentityUser> userManager)
        {
            _postRepository = postRepository;
            _blogRepository = blogRepository;
            _userManager = userManager;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var blogs = _blogRepository.GetAllBlogs(user);
            var blogViewModel = new BlogViewModel()
            {
                Title = "My blogs",
                Blogs = blogs.ToList()
            };
            return View(blogViewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var blog = _blogRepository.GetBlogById(id);
            var posts = _postRepository.GetBlogPosts(blog);
            var postViewModel = new PostViewModel()
            {
                Title = "My posts",
                Posts = posts.ToList()
            };
            return View(postViewModel);
        }

        [HttpGet]
        public IActionResult AddBlog()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddBlog(Blog blog)
        {
            if (ModelState.IsValid)
            {
                blog.User = await _userManager.GetUserAsync(HttpContext.User);
                _blogRepository.AddBlog(blog);

                return RedirectToAction("Index");
            }
            else
            {
                return View(blog);
            }
        }
    }
}

Lolo/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lolo.Models;
using Lolo.Models.Interfaces;
using Lolo.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Lolo.Controllers
{
    [Authorize]
    public class TagController : Controller
    {
        private readonly ITagRepository _tagRepository;
        private readonly AppDbContext _context;


        public TagController(ITagRepository tagRepository, AppDbContext context)
        {
            _tagRepository = tagRepository;
            _context = context;
        }
        public IActionResult Index()
        {
            //var post = _context.Posts
            //   .Include(p => p.Tags)
            //   .ThenInclude(g => g.Tag)
            //   .FirstOrDefault(p => p.PostId == id);
            var tags = _context.PostTags
                .Include(p => p.Tag);
            var tagViewModel = new TagViewModel
            {
                Tags = tags.ToList()
            };
            // var tags = _tagRepository.GetAllTags();
            return View(tagViewModel);
        }
    }
}

Lolo/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
<form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
      method="post" class="navbar-right">
    <ul class="nav navbar-nav navbar-right">
        <li><a href="javascript:document.getElementById('logoutForm').submit()">@User.Identity.Name - Log Out</a></li>
    </ul>
</form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register">Register</a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login">Log in</a></li>
    </ul>
}

Lolo/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Lolo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="SHORTCUT ICON" href="~/images/icon.png" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/normalize.css" />
    <link rel="stylesheet" type="text/css" href="~/css/demo.css" />
    <link rel="stylesheet" type="text/css" href="~/css/style.css" />
    <link rel="stylesheet" type="text/css" href="~/css/card.css" id="cord" />
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.4.2/css/all.css' integrity='sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns' crossorigin='anonymous'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
        <nav class="navbar navbar-inverse">
            <style>
                .navbar {
                    margin: 0px;
                }
            </style>
            <div class="container-fluid">
                <ul class="nav navbar-nav">
                    <li class="active"><a asp-controller="Home" asp-action="Index"><i class='fas fa-home'></i> Lolo</a></li>
                    @if (User.IsInRole("user"))
                    {
                        <li class="active"><a asp-controller="Blog" asp-action="Index"><i class='fas fa-user'></i></a></li>
                    }
                    @if (User.IsInRole("admin"))
                    {
                        <li class="active"><a asp-controller="Admin" asp-action="Index"><i class='fas fa-user-friends'></i></a></li>
                    }
                    @if (User.IsInRole("user"))
                    {
                        <li class="active"><a asp-controller="Blog" asp-action="AddBlog"><i class='fas fa-plus'></i> @SharedLocalizer["AddBlog"]</a></li>
                        <li class="active"><a asp-controller="Post" asp-action="AddPost"><i class='fas fa-plus'></i> @SharedLocalizer["AddPost"]</a></li>
                        @*<li class="active"><a href="~/index.html"><i class='fas fa-users'></i></a></li>*@

                        <li class="active"><a asp-controller="Home" asp-action="Users"><i class='fas fa-users'></i></a></li>
                        <li class="active"><a asp-controller="Tag" asp-action="Index"><i class='fas fa-tags'></i></a></li>
                    }
                </ul>
                @await Component.InvokeAsync("LoginStatus")
                @await Html.PartialAsync("_SelectLanguagePartial")
            </div>
        </nav>
    @RenderBody()
    <vk></vk>
</body>
</html>

Lolo/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:10px;"
      asp-route-returnUrl="@Context.Request.Path"
      method="post" class="form-horizontal">
    @*@Localizer["Language:"]*@
    <div class="col-sm-2">
        <select style="background-color:#222222; border:solid #141414" class="form-control" name="culture" onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems"></select>
    </div>
   
</form>